server:
  port: 8762

spring:
  application:
    name: msvc-eureka

eureka:
  instance:
    hostname: msvc-eureka
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://msvc-eureka:8762/eureka/